// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// knotindex
int knotindex(double x, Eigen::VectorXd t);
RcppExport SEXP _SIdrfDLNM_knotindex(SEXP xSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(knotindex(x, t));
    return rcpp_result_gen;
END_RCPP
}
// Bspline
double Bspline(double x, int j, Eigen::VectorXd t, int p);
RcppExport SEXP _SIdrfDLNM_Bspline(SEXP xSEXP, SEXP jSEXP, SEXP tSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(Bspline(x, j, t, p));
    return rcpp_result_gen;
END_RCPP
}
// Bsplinevec
Eigen::VectorXd Bsplinevec(double x, Eigen::VectorXd t, int p);
RcppExport SEXP _SIdrfDLNM_Bsplinevec(SEXP xSEXP, SEXP tSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(Bsplinevec(x, t, p));
    return rcpp_result_gen;
END_RCPP
}
// BsplinevecCon
Eigen::VectorXd BsplinevecCon(double x, Eigen::VectorXd t, int p, Eigen::MatrixXd Z);
RcppExport SEXP _SIdrfDLNM_BsplinevecCon(SEXP xSEXP, SEXP tSEXP, SEXP pSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(BsplinevecCon(x, t, p, Z));
    return rcpp_result_gen;
END_RCPP
}
// BsplinevecConJ
double BsplinevecConJ(double x, Eigen::VectorXd t, int p, Eigen::MatrixXd Z, int j);
RcppExport SEXP _SIdrfDLNM_BsplinevecConJ(SEXP xSEXP, SEXP tSEXP, SEXP pSEXP, SEXP ZSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    rcpp_result_gen = Rcpp::wrap(BsplinevecConJ(x, t, p, Z, j));
    return rcpp_result_gen;
END_RCPP
}
// Bsplinevec2
Eigen::VectorXd Bsplinevec2(double x, Eigen::VectorXd t, int p);
RcppExport SEXP _SIdrfDLNM_Bsplinevec2(SEXP xSEXP, SEXP tSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(Bsplinevec2(x, t, p));
    return rcpp_result_gen;
END_RCPP
}
// Bsplinevec2Con
Eigen::VectorXd Bsplinevec2Con(double x, Eigen::VectorXd t, int p, Eigen::MatrixXd Z);
RcppExport SEXP _SIdrfDLNM_Bsplinevec2Con(SEXP xSEXP, SEXP tSEXP, SEXP pSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(Bsplinevec2Con(x, t, p, Z));
    return rcpp_result_gen;
END_RCPP
}
// Bsplinevec2ConJ
double Bsplinevec2ConJ(double x, Eigen::VectorXd t, int p, Eigen::MatrixXd Z, int j);
RcppExport SEXP _SIdrfDLNM_Bsplinevec2ConJ(SEXP xSEXP, SEXP tSEXP, SEXP pSEXP, SEXP ZSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    rcpp_result_gen = Rcpp::wrap(Bsplinevec2ConJ(x, t, p, Z, j));
    return rcpp_result_gen;
END_RCPP
}
// BsplinevecFill
void BsplinevecFill(double x, Eigen::VectorXd t, int p, int col, Eigen::SparseMatrix<double>& Gx);
RcppExport SEXP _SIdrfDLNM_BsplinevecFill(SEXP xSEXP, SEXP tSEXP, SEXP pSEXP, SEXP colSEXP, SEXP GxSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type col(colSEXP);
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double>& >::type Gx(GxSEXP);
    BsplinevecFill(x, t, p, col, Gx);
    return R_NilValue;
END_RCPP
}
// Bsplinevec2Fill
void Bsplinevec2Fill(double x, Eigen::VectorXd t, int p, int col, Eigen::SparseMatrix<double>& Gx);
RcppExport SEXP _SIdrfDLNM_Bsplinevec2Fill(SEXP xSEXP, SEXP tSEXP, SEXP pSEXP, SEXP colSEXP, SEXP GxSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type col(colSEXP);
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double>& >::type Gx(GxSEXP);
    Bsplinevec2Fill(x, t, p, col, Gx);
    return R_NilValue;
END_RCPP
}
// SurfaceEval
double SurfaceEval(double E, double Ecen, int l, Eigen::VectorXd alphaf, Eigen::VectorXd knotsf, Eigen::MatrixXd Z, Eigen::MatrixXd Blag);
RcppExport SEXP _SIdrfDLNM_SurfaceEval(SEXP ESEXP, SEXP EcenSEXP, SEXP lSEXP, SEXP alphafSEXP, SEXP knotsfSEXP, SEXP ZSEXP, SEXP BlagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type E(ESEXP);
    Rcpp::traits::input_parameter< double >::type Ecen(EcenSEXP);
    Rcpp::traits::input_parameter< int >::type l(lSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type alphaf(alphafSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type knotsf(knotsfSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Blag(BlagSEXP);
    rcpp_result_gen = Rcpp::wrap(SurfaceEval(E, Ecen, l, alphaf, knotsf, Z, Blag));
    return rcpp_result_gen;
END_RCPP
}
// SurfaceCI
Eigen::MatrixXd SurfaceCI(Eigen::MatrixXd gridEl, Eigen::MatrixXd alpha_f_sample, double Ecen, Eigen::VectorXd knotsf, Eigen::MatrixXd Z, Eigen::MatrixXd Blag);
RcppExport SEXP _SIdrfDLNM_SurfaceCI(SEXP gridElSEXP, SEXP alpha_f_sampleSEXP, SEXP EcenSEXP, SEXP knotsfSEXP, SEXP ZSEXP, SEXP BlagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type gridEl(gridElSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type alpha_f_sample(alpha_f_sampleSEXP);
    Rcpp::traits::input_parameter< double >::type Ecen(EcenSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type knotsf(knotsfSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Blag(BlagSEXP);
    rcpp_result_gen = Rcpp::wrap(SurfaceCI(gridEl, alpha_f_sample, Ecen, knotsf, Z, Blag));
    return rcpp_result_gen;
END_RCPP
}
// Integral
List Integral(Eigen::VectorXd knots_x, Eigen::VectorXd knots_w, int kx, int kw, double maxL, Eigen::MatrixXd Zx, Eigen::MatrixXd Zw, Eigen::VectorXd t, Eigen::VectorXd alphax, bool OnlyAlphaxD);
RcppExport SEXP _SIdrfDLNM_Integral(SEXP knots_xSEXP, SEXP knots_wSEXP, SEXP kxSEXP, SEXP kwSEXP, SEXP maxLSEXP, SEXP ZxSEXP, SEXP ZwSEXP, SEXP tSEXP, SEXP alphaxSEXP, SEXP OnlyAlphaxDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type knots_x(knots_xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type knots_w(knots_wSEXP);
    Rcpp::traits::input_parameter< int >::type kx(kxSEXP);
    Rcpp::traits::input_parameter< int >::type kw(kwSEXP);
    Rcpp::traits::input_parameter< double >::type maxL(maxLSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Zx(ZxSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Zw(ZwSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type alphax(alphaxSEXP);
    Rcpp::traits::input_parameter< bool >::type OnlyAlphaxD(OnlyAlphaxDSEXP);
    rcpp_result_gen = Rcpp::wrap(Integral(knots_x, knots_w, kx, kw, maxL, Zx, Zw, t, alphax, OnlyAlphaxD));
    return rcpp_result_gen;
END_RCPP
}
// deBoor
double deBoor(double x, Eigen::VectorXd t, Eigen::VectorXd beta, int p);
RcppExport SEXP _SIdrfDLNM_deBoor(SEXP xSEXP, SEXP tSEXP, SEXP betaSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(deBoor(x, t, beta, p));
    return rcpp_result_gen;
END_RCPP
}
// Integral_interpolate
List Integral_interpolate(Eigen::VectorXd knots_x, Eigen::VectorXd knots_w, int kx, int kw, double maxL, Eigen::MatrixXd Zw, Eigen::VectorXd t, Eigen::VectorXd alphax, bool OnlyAlphaxD);
RcppExport SEXP _SIdrfDLNM_Integral_interpolate(SEXP knots_xSEXP, SEXP knots_wSEXP, SEXP kxSEXP, SEXP kwSEXP, SEXP maxLSEXP, SEXP ZwSEXP, SEXP tSEXP, SEXP alphaxSEXP, SEXP OnlyAlphaxDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type knots_x(knots_xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type knots_w(knots_wSEXP);
    Rcpp::traits::input_parameter< int >::type kx(kxSEXP);
    Rcpp::traits::input_parameter< int >::type kw(kwSEXP);
    Rcpp::traits::input_parameter< double >::type maxL(maxLSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Zw(ZwSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type t(tSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type alphax(alphaxSEXP);
    Rcpp::traits::input_parameter< bool >::type OnlyAlphaxD(OnlyAlphaxDSEXP);
    rcpp_result_gen = Rcpp::wrap(Integral_interpolate(knots_x, knots_w, kx, kw, maxL, Zw, t, alphax, OnlyAlphaxD));
    return rcpp_result_gen;
END_RCPP
}
// Interpolate
Eigen::VectorXd Interpolate(Eigen::SparseMatrix<double> X, Eigen::VectorXd y);
RcppExport SEXP _SIdrfDLNM_Interpolate(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double> >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(Interpolate(X, y));
    return rcpp_result_gen;
END_RCPP
}
// sidDLNMbuild
List sidDLNMbuild(const Eigen::VectorXd R_y, const List R_B_inner_list, const Eigen::VectorXd R_knots_f, const Eigen::VectorXd R_knots_w, const Eigen::MatrixXd R_Sw, const Eigen::MatrixXd R_SwR, const Eigen::MatrixXd R_Sf, const Eigen::MatrixXd R_SfR, const Eigen::MatrixXd R_Xrand, const Eigen::MatrixXd R_Xfix, const Eigen::MatrixXd R_Zf, const Eigen::VectorXd R_Xoffset, const Eigen::VectorXd R_r, const Eigen::MatrixXd R_Bindex, Eigen::VectorXd R_alpha_f, Eigen::VectorXd R_con_index_par, double R_log_theta, double R_log_smoothing_f, double R_log_smoothing_w, Eigen::VectorXd R_betaR, Eigen::VectorXd R_betaF, Eigen::VectorXd R_logsmoothing);
RcppExport SEXP _SIdrfDLNM_sidDLNMbuild(SEXP R_ySEXP, SEXP R_B_inner_listSEXP, SEXP R_knots_fSEXP, SEXP R_knots_wSEXP, SEXP R_SwSEXP, SEXP R_SwRSEXP, SEXP R_SfSEXP, SEXP R_SfRSEXP, SEXP R_XrandSEXP, SEXP R_XfixSEXP, SEXP R_ZfSEXP, SEXP R_XoffsetSEXP, SEXP R_rSEXP, SEXP R_BindexSEXP, SEXP R_alpha_fSEXP, SEXP R_con_index_parSEXP, SEXP R_log_thetaSEXP, SEXP R_log_smoothing_fSEXP, SEXP R_log_smoothing_wSEXP, SEXP R_betaRSEXP, SEXP R_betaFSEXP, SEXP R_logsmoothingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type R_y(R_ySEXP);
    Rcpp::traits::input_parameter< const List >::type R_B_inner_list(R_B_inner_listSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type R_knots_f(R_knots_fSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type R_knots_w(R_knots_wSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type R_Sw(R_SwSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type R_SwR(R_SwRSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type R_Sf(R_SfSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type R_SfR(R_SfRSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type R_Xrand(R_XrandSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type R_Xfix(R_XfixSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type R_Zf(R_ZfSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type R_Xoffset(R_XoffsetSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type R_r(R_rSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type R_Bindex(R_BindexSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_alpha_f(R_alpha_fSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_con_index_par(R_con_index_parSEXP);
    Rcpp::traits::input_parameter< double >::type R_log_theta(R_log_thetaSEXP);
    Rcpp::traits::input_parameter< double >::type R_log_smoothing_f(R_log_smoothing_fSEXP);
    Rcpp::traits::input_parameter< double >::type R_log_smoothing_w(R_log_smoothing_wSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_betaR(R_betaRSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_betaF(R_betaFSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_logsmoothing(R_logsmoothingSEXP);
    rcpp_result_gen = Rcpp::wrap(sidDLNMbuild(R_y, R_B_inner_list, R_knots_f, R_knots_w, R_Sw, R_SwR, R_Sf, R_SfR, R_Xrand, R_Xfix, R_Zf, R_Xoffset, R_r, R_Bindex, R_alpha_f, R_con_index_par, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing));
    return rcpp_result_gen;
END_RCPP
}
// sidDLNMopt
List sidDLNMopt(SEXP ptr, SEXP ptrcppad, Eigen::VectorXd R_alpha_f, Eigen::VectorXd R_con_index_par, double R_log_theta, double R_log_smoothing_f, double R_log_smoothing_w, Eigen::VectorXd R_betaR, Eigen::VectorXd R_betaF, Eigen::VectorXd R_logsmoothing, bool ifgradient, bool verbose);
RcppExport SEXP _SIdrfDLNM_sidDLNMopt(SEXP ptrSEXP, SEXP ptrcppadSEXP, SEXP R_alpha_fSEXP, SEXP R_con_index_parSEXP, SEXP R_log_thetaSEXP, SEXP R_log_smoothing_fSEXP, SEXP R_log_smoothing_wSEXP, SEXP R_betaRSEXP, SEXP R_betaFSEXP, SEXP R_logsmoothingSEXP, SEXP ifgradientSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ptrcppad(ptrcppadSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_alpha_f(R_alpha_fSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_con_index_par(R_con_index_parSEXP);
    Rcpp::traits::input_parameter< double >::type R_log_theta(R_log_thetaSEXP);
    Rcpp::traits::input_parameter< double >::type R_log_smoothing_f(R_log_smoothing_fSEXP);
    Rcpp::traits::input_parameter< double >::type R_log_smoothing_w(R_log_smoothing_wSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_betaR(R_betaRSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_betaF(R_betaFSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type R_logsmoothing(R_logsmoothingSEXP);
    Rcpp::traits::input_parameter< bool >::type ifgradient(ifgradientSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(sidDLNMopt(ptr, ptrcppad, R_alpha_f, R_con_index_par, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing, ifgradient, verbose));
    return rcpp_result_gen;
END_RCPP
}
// sidDLNMCI
List sidDLNMCI(SEXP ptr, const int Rci, const int rseed, bool ifeta, bool verbose, Rcpp::Nullable<Rcpp::NumericMatrix> R_he_input);
RcppExport SEXP _SIdrfDLNM_sidDLNMCI(SEXP ptrSEXP, SEXP RciSEXP, SEXP rseedSEXP, SEXP ifetaSEXP, SEXP verboseSEXP, SEXP R_he_inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< const int >::type Rci(RciSEXP);
    Rcpp::traits::input_parameter< const int >::type rseed(rseedSEXP);
    Rcpp::traits::input_parameter< bool >::type ifeta(ifetaSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type R_he_input(R_he_inputSEXP);
    rcpp_result_gen = Rcpp::wrap(sidDLNMCI(ptr, Rci, rseed, ifeta, verbose, R_he_input));
    return rcpp_result_gen;
END_RCPP
}
// ConditionalAICsidDLNM
List ConditionalAICsidDLNM(SEXP ptr, SEXP ptrcppad, Eigen::MatrixXd Vrho, bool verbose, bool marginal);
RcppExport SEXP _SIdrfDLNM_ConditionalAICsidDLNM(SEXP ptrSEXP, SEXP ptrcppadSEXP, SEXP VrhoSEXP, SEXP verboseSEXP, SEXP marginalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ptrcppad(ptrcppadSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Vrho(VrhoSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type marginal(marginalSEXP);
    rcpp_result_gen = Rcpp::wrap(ConditionalAICsidDLNM(ptr, ptrcppad, Vrho, verbose, marginal));
    return rcpp_result_gen;
END_RCPP
}
// NCVsidDLNM
List NCVsidDLNM(SEXP ptr, const List nei_list, bool verbose, int nthreads);
RcppExport SEXP _SIdrfDLNM_NCVsidDLNM(SEXP ptrSEXP, SEXP nei_listSEXP, SEXP verboseSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< const List >::type nei_list(nei_listSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(NCVsidDLNM(ptr, nei_list, verbose, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// BsplinevecCon1st
Eigen::VectorXd BsplinevecCon1st(double x, const Eigen::VectorXd& t, int p, Eigen::MatrixXd Z);
RcppExport SEXP _SIdrfDLNM_BsplinevecCon1st(SEXP xSEXP, SEXP tSEXP, SEXP pSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(BsplinevecCon1st(x, t, p, Z));
    return rcpp_result_gen;
END_RCPP
}
// BsplinevecCon2nd
Eigen::VectorXd BsplinevecCon2nd(double x, const Eigen::VectorXd& t, int p, Eigen::MatrixXd Z);
RcppExport SEXP _SIdrfDLNM_BsplinevecCon2nd(SEXP xSEXP, SEXP tSEXP, SEXP pSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(BsplinevecCon2nd(x, t, p, Z));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SIdrfDLNM_knotindex", (DL_FUNC) &_SIdrfDLNM_knotindex, 2},
    {"_SIdrfDLNM_Bspline", (DL_FUNC) &_SIdrfDLNM_Bspline, 4},
    {"_SIdrfDLNM_Bsplinevec", (DL_FUNC) &_SIdrfDLNM_Bsplinevec, 3},
    {"_SIdrfDLNM_BsplinevecCon", (DL_FUNC) &_SIdrfDLNM_BsplinevecCon, 4},
    {"_SIdrfDLNM_BsplinevecConJ", (DL_FUNC) &_SIdrfDLNM_BsplinevecConJ, 5},
    {"_SIdrfDLNM_Bsplinevec2", (DL_FUNC) &_SIdrfDLNM_Bsplinevec2, 3},
    {"_SIdrfDLNM_Bsplinevec2Con", (DL_FUNC) &_SIdrfDLNM_Bsplinevec2Con, 4},
    {"_SIdrfDLNM_Bsplinevec2ConJ", (DL_FUNC) &_SIdrfDLNM_Bsplinevec2ConJ, 5},
    {"_SIdrfDLNM_BsplinevecFill", (DL_FUNC) &_SIdrfDLNM_BsplinevecFill, 5},
    {"_SIdrfDLNM_Bsplinevec2Fill", (DL_FUNC) &_SIdrfDLNM_Bsplinevec2Fill, 5},
    {"_SIdrfDLNM_SurfaceEval", (DL_FUNC) &_SIdrfDLNM_SurfaceEval, 7},
    {"_SIdrfDLNM_SurfaceCI", (DL_FUNC) &_SIdrfDLNM_SurfaceCI, 6},
    {"_SIdrfDLNM_Integral", (DL_FUNC) &_SIdrfDLNM_Integral, 10},
    {"_SIdrfDLNM_deBoor", (DL_FUNC) &_SIdrfDLNM_deBoor, 4},
    {"_SIdrfDLNM_Integral_interpolate", (DL_FUNC) &_SIdrfDLNM_Integral_interpolate, 9},
    {"_SIdrfDLNM_Interpolate", (DL_FUNC) &_SIdrfDLNM_Interpolate, 2},
    {"_SIdrfDLNM_sidDLNMbuild", (DL_FUNC) &_SIdrfDLNM_sidDLNMbuild, 22},
    {"_SIdrfDLNM_sidDLNMopt", (DL_FUNC) &_SIdrfDLNM_sidDLNMopt, 12},
    {"_SIdrfDLNM_sidDLNMCI", (DL_FUNC) &_SIdrfDLNM_sidDLNMCI, 6},
    {"_SIdrfDLNM_ConditionalAICsidDLNM", (DL_FUNC) &_SIdrfDLNM_ConditionalAICsidDLNM, 5},
    {"_SIdrfDLNM_NCVsidDLNM", (DL_FUNC) &_SIdrfDLNM_NCVsidDLNM, 4},
    {"_SIdrfDLNM_BsplinevecCon1st", (DL_FUNC) &_SIdrfDLNM_BsplinevecCon1st, 4},
    {"_SIdrfDLNM_BsplinevecCon2nd", (DL_FUNC) &_SIdrfDLNM_BsplinevecCon2nd, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SIdrfDLNM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
