# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

knotindex <- function(x, t) {
    .Call(`_SIdrfDLNM_knotindex`, x, t)
}

Bspline <- function(x, j, t, p) {
    .Call(`_SIdrfDLNM_Bspline`, x, j, t, p)
}

Bsplinevec <- function(x, t, p) {
    .Call(`_SIdrfDLNM_Bsplinevec`, x, t, p)
}

BsplinevecCon <- function(x, t, p, Z) {
    .Call(`_SIdrfDLNM_BsplinevecCon`, x, t, p, Z)
}

BsplinevecConJ <- function(x, t, p, Z, j) {
    .Call(`_SIdrfDLNM_BsplinevecConJ`, x, t, p, Z, j)
}

Bsplinevec2 <- function(x, t, p) {
    .Call(`_SIdrfDLNM_Bsplinevec2`, x, t, p)
}

Bsplinevec2Con <- function(x, t, p, Z) {
    .Call(`_SIdrfDLNM_Bsplinevec2Con`, x, t, p, Z)
}

Bsplinevec2ConJ <- function(x, t, p, Z, j) {
    .Call(`_SIdrfDLNM_Bsplinevec2ConJ`, x, t, p, Z, j)
}

BsplinevecFill <- function(x, t, p, col, Gx) {
    invisible(.Call(`_SIdrfDLNM_BsplinevecFill`, x, t, p, col, Gx))
}

Bsplinevec2Fill <- function(x, t, p, col, Gx) {
    invisible(.Call(`_SIdrfDLNM_Bsplinevec2Fill`, x, t, p, col, Gx))
}

SurfaceEval <- function(E, Ecen, l, alphaf, knotsf, Z, Blag) {
    .Call(`_SIdrfDLNM_SurfaceEval`, E, Ecen, l, alphaf, knotsf, Z, Blag)
}

SurfaceCI <- function(gridEl, alpha_f_sample, Ecen, knotsf, Z, Blag) {
    .Call(`_SIdrfDLNM_SurfaceCI`, gridEl, alpha_f_sample, Ecen, knotsf, Z, Blag)
}

Integral <- function(knots_x, knots_w, kx, kw, maxL, Zx, Zw, t, alphax, OnlyAlphaxD) {
    .Call(`_SIdrfDLNM_Integral`, knots_x, knots_w, kx, kw, maxL, Zx, Zw, t, alphax, OnlyAlphaxD)
}

deBoor <- function(x, t, beta, p) {
    .Call(`_SIdrfDLNM_deBoor`, x, t, beta, p)
}

Integral_interpolate <- function(knots_x, knots_w, kx, kw, maxL, Zw, t, alphax, OnlyAlphaxD) {
    .Call(`_SIdrfDLNM_Integral_interpolate`, knots_x, knots_w, kx, kw, maxL, Zw, t, alphax, OnlyAlphaxD)
}

Interpolate <- function(X, y) {
    .Call(`_SIdrfDLNM_Interpolate`, X, y)
}

sidDLNMbuild <- function(R_y, R_B_inner_list, R_knots_f, R_knots_w, R_Sw, R_SwR, R_Sf, R_SfR, R_Xrand, R_Xfix, R_Zf, R_Xoffset, R_r, R_Bindex, R_alpha_f, R_con_index_par, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing) {
    .Call(`_SIdrfDLNM_sidDLNMbuild`, R_y, R_B_inner_list, R_knots_f, R_knots_w, R_Sw, R_SwR, R_Sf, R_SfR, R_Xrand, R_Xfix, R_Zf, R_Xoffset, R_r, R_Bindex, R_alpha_f, R_con_index_par, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing)
}

sidDLNMopt <- function(ptr, ptrcppad, R_alpha_f, R_con_index_par, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing, ifgradient, verbose) {
    .Call(`_SIdrfDLNM_sidDLNMopt`, ptr, ptrcppad, R_alpha_f, R_con_index_par, R_log_theta, R_log_smoothing_f, R_log_smoothing_w, R_betaR, R_betaF, R_logsmoothing, ifgradient, verbose)
}

sidDLNMCI <- function(ptr, Rci, rseed, ifeta, verbose, R_he_input = NULL) {
    .Call(`_SIdrfDLNM_sidDLNMCI`, ptr, Rci, rseed, ifeta, verbose, R_he_input)
}

ConditionalAICsidDLNM <- function(ptr, ptrcppad, Vrho, verbose = FALSE, marginal = FALSE) {
    .Call(`_SIdrfDLNM_ConditionalAICsidDLNM`, ptr, ptrcppad, Vrho, verbose, marginal)
}

NCVsidDLNM <- function(ptr, nei_list, verbose = FALSE, nthreads = 1L) {
    .Call(`_SIdrfDLNM_NCVsidDLNM`, ptr, nei_list, verbose, nthreads)
}

BsplinevecCon1st <- function(x, t, p, Z) {
    .Call(`_SIdrfDLNM_BsplinevecCon1st`, x, t, p, Z)
}

BsplinevecCon2nd <- function(x, t, p, Z) {
    .Call(`_SIdrfDLNM_BsplinevecCon2nd`, x, t, p, Z)
}

